name: Run Email Agent Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Every hour (UTC)
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore credentials and env
        run: |
          echo "${{ secrets.CREDENTIALS_B64 }}" | base64 -d > credentials.json
          echo "${{ secrets.TOKEN_B64 }}" | base64 -d > token.json
          echo "${{ secrets.ENV_B64 }}" | base64 -d > .env

      - name: Run Agent
        run: |
          python mian.py
